config:
 plugins:
  metrics-by-endpoint: {}
 target: "http://127.0.0.1:56003/api/mocks/mockingusers"
 phases:
  - duration: 10
    arrivalRate: 5
    name: "Prueba rendimiento Login / Registro"
scenarios:
 - name: "Sessions Flow (registro + login)"
   flow:
    - get:
       url: "/"
    - log: "usuarios creados correctamente"