apiVersion: apps/v1
kind: Service
metadata:
  name: usersservice
spec:
  selector:
    app: userspods
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usersdeploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: userspods
  template:
    metadata:
      labels:
        app: userspods
    spec:
      containers:
        - name: usercontainer
          image: matiascatuogno/adoptme:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: NODE_ENV
              value: production
            - name: MONGO_URL
              value: {{MONGO_URL}}
          imagePullPolicy: Always